// source: pkg/drivers/instance/vanilla/driver.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var google_protobuf_struct_pb = require('google-protobuf/google/protobuf/struct_pb.js');
goog.object.extend(proto, google_protobuf_struct_pb);
var pkg_instances_proto_instances_pb = require('../../../../pkg/instances/proto/instances_pb.js');
goog.object.extend(proto, pkg_instances_proto_instances_pb);
var pkg_services_providers_proto_services_providers_pb = require('../../../../pkg/services_providers/proto/services_providers_pb.js');
goog.object.extend(proto, pkg_services_providers_proto_services_providers_pb);
goog.exportSymbol('proto.nocloud.instance.driver.vanilla.DeployRequest', null, global);
goog.exportSymbol('proto.nocloud.instance.driver.vanilla.DeployResponse', null, global);
goog.exportSymbol('proto.nocloud.instance.driver.vanilla.GetTypeRequest', null, global);
goog.exportSymbol('proto.nocloud.instance.driver.vanilla.GetTypeResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nocloud.instance.driver.vanilla.GetTypeRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.nocloud.instance.driver.vanilla.GetTypeRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nocloud.instance.driver.vanilla.GetTypeRequest.displayName = 'proto.nocloud.instance.driver.vanilla.GetTypeRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nocloud.instance.driver.vanilla.GetTypeResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.nocloud.instance.driver.vanilla.GetTypeResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nocloud.instance.driver.vanilla.GetTypeResponse.displayName = 'proto.nocloud.instance.driver.vanilla.GetTypeResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nocloud.instance.driver.vanilla.DeployRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.nocloud.instance.driver.vanilla.DeployRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nocloud.instance.driver.vanilla.DeployRequest.displayName = 'proto.nocloud.instance.driver.vanilla.DeployRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nocloud.instance.driver.vanilla.DeployResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.nocloud.instance.driver.vanilla.DeployResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nocloud.instance.driver.vanilla.DeployResponse.displayName = 'proto.nocloud.instance.driver.vanilla.DeployResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.nocloud.instance.driver.vanilla.GetTypeRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.nocloud.instance.driver.vanilla.GetTypeRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.nocloud.instance.driver.vanilla.GetTypeRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nocloud.instance.driver.vanilla.GetTypeRequest.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nocloud.instance.driver.vanilla.GetTypeRequest}
 */
proto.nocloud.instance.driver.vanilla.GetTypeRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.nocloud.instance.driver.vanilla.GetTypeRequest;
  return proto.nocloud.instance.driver.vanilla.GetTypeRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nocloud.instance.driver.vanilla.GetTypeRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nocloud.instance.driver.vanilla.GetTypeRequest}
 */
proto.nocloud.instance.driver.vanilla.GetTypeRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nocloud.instance.driver.vanilla.GetTypeRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.nocloud.instance.driver.vanilla.GetTypeRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nocloud.instance.driver.vanilla.GetTypeRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nocloud.instance.driver.vanilla.GetTypeRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.nocloud.instance.driver.vanilla.GetTypeResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.nocloud.instance.driver.vanilla.GetTypeResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.nocloud.instance.driver.vanilla.GetTypeResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nocloud.instance.driver.vanilla.GetTypeResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nocloud.instance.driver.vanilla.GetTypeResponse}
 */
proto.nocloud.instance.driver.vanilla.GetTypeResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.nocloud.instance.driver.vanilla.GetTypeResponse;
  return proto.nocloud.instance.driver.vanilla.GetTypeResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nocloud.instance.driver.vanilla.GetTypeResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nocloud.instance.driver.vanilla.GetTypeResponse}
 */
proto.nocloud.instance.driver.vanilla.GetTypeResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setType(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nocloud.instance.driver.vanilla.GetTypeResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.nocloud.instance.driver.vanilla.GetTypeResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nocloud.instance.driver.vanilla.GetTypeResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nocloud.instance.driver.vanilla.GetTypeResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string type = 1;
 * @return {string}
 */
proto.nocloud.instance.driver.vanilla.GetTypeResponse.prototype.getType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.nocloud.instance.driver.vanilla.GetTypeResponse} returns this
 */
proto.nocloud.instance.driver.vanilla.GetTypeResponse.prototype.setType = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.nocloud.instance.driver.vanilla.DeployRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.nocloud.instance.driver.vanilla.DeployRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.nocloud.instance.driver.vanilla.DeployRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nocloud.instance.driver.vanilla.DeployRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    group: (f = msg.getGroup()) && pkg_instances_proto_instances_pb.InstancesGroup.toObject(includeInstance, f),
    servicesProvider: (f = msg.getServicesProvider()) && pkg_services_providers_proto_services_providers_pb.ServicesProvider.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nocloud.instance.driver.vanilla.DeployRequest}
 */
proto.nocloud.instance.driver.vanilla.DeployRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.nocloud.instance.driver.vanilla.DeployRequest;
  return proto.nocloud.instance.driver.vanilla.DeployRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nocloud.instance.driver.vanilla.DeployRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nocloud.instance.driver.vanilla.DeployRequest}
 */
proto.nocloud.instance.driver.vanilla.DeployRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new pkg_instances_proto_instances_pb.InstancesGroup;
      reader.readMessage(value,pkg_instances_proto_instances_pb.InstancesGroup.deserializeBinaryFromReader);
      msg.setGroup(value);
      break;
    case 2:
      var value = new pkg_services_providers_proto_services_providers_pb.ServicesProvider;
      reader.readMessage(value,pkg_services_providers_proto_services_providers_pb.ServicesProvider.deserializeBinaryFromReader);
      msg.setServicesProvider(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nocloud.instance.driver.vanilla.DeployRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.nocloud.instance.driver.vanilla.DeployRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nocloud.instance.driver.vanilla.DeployRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nocloud.instance.driver.vanilla.DeployRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getGroup();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      pkg_instances_proto_instances_pb.InstancesGroup.serializeBinaryToWriter
    );
  }
  f = message.getServicesProvider();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      pkg_services_providers_proto_services_providers_pb.ServicesProvider.serializeBinaryToWriter
    );
  }
};


/**
 * optional nocloud.instances.InstancesGroup group = 1;
 * @return {?proto.nocloud.instances.InstancesGroup}
 */
proto.nocloud.instance.driver.vanilla.DeployRequest.prototype.getGroup = function() {
  return /** @type{?proto.nocloud.instances.InstancesGroup} */ (
    jspb.Message.getWrapperField(this, pkg_instances_proto_instances_pb.InstancesGroup, 1));
};


/**
 * @param {?proto.nocloud.instances.InstancesGroup|undefined} value
 * @return {!proto.nocloud.instance.driver.vanilla.DeployRequest} returns this
*/
proto.nocloud.instance.driver.vanilla.DeployRequest.prototype.setGroup = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.nocloud.instance.driver.vanilla.DeployRequest} returns this
 */
proto.nocloud.instance.driver.vanilla.DeployRequest.prototype.clearGroup = function() {
  return this.setGroup(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.nocloud.instance.driver.vanilla.DeployRequest.prototype.hasGroup = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional nocloud.services_providers.ServicesProvider services_provider = 2;
 * @return {?proto.nocloud.services_providers.ServicesProvider}
 */
proto.nocloud.instance.driver.vanilla.DeployRequest.prototype.getServicesProvider = function() {
  return /** @type{?proto.nocloud.services_providers.ServicesProvider} */ (
    jspb.Message.getWrapperField(this, pkg_services_providers_proto_services_providers_pb.ServicesProvider, 2));
};


/**
 * @param {?proto.nocloud.services_providers.ServicesProvider|undefined} value
 * @return {!proto.nocloud.instance.driver.vanilla.DeployRequest} returns this
*/
proto.nocloud.instance.driver.vanilla.DeployRequest.prototype.setServicesProvider = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.nocloud.instance.driver.vanilla.DeployRequest} returns this
 */
proto.nocloud.instance.driver.vanilla.DeployRequest.prototype.clearServicesProvider = function() {
  return this.setServicesProvider(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.nocloud.instance.driver.vanilla.DeployRequest.prototype.hasServicesProvider = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.nocloud.instance.driver.vanilla.DeployResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.nocloud.instance.driver.vanilla.DeployResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.nocloud.instance.driver.vanilla.DeployResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nocloud.instance.driver.vanilla.DeployResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    group: (f = msg.getGroup()) && pkg_instances_proto_instances_pb.InstancesGroup.toObject(includeInstance, f),
    groupDataMap: (f = msg.getGroupDataMap()) ? f.toObject(includeInstance, proto.google.protobuf.Value.toObject) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nocloud.instance.driver.vanilla.DeployResponse}
 */
proto.nocloud.instance.driver.vanilla.DeployResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.nocloud.instance.driver.vanilla.DeployResponse;
  return proto.nocloud.instance.driver.vanilla.DeployResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nocloud.instance.driver.vanilla.DeployResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nocloud.instance.driver.vanilla.DeployResponse}
 */
proto.nocloud.instance.driver.vanilla.DeployResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new pkg_instances_proto_instances_pb.InstancesGroup;
      reader.readMessage(value,pkg_instances_proto_instances_pb.InstancesGroup.deserializeBinaryFromReader);
      msg.setGroup(value);
      break;
    case 2:
      var value = msg.getGroupDataMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.google.protobuf.Value.deserializeBinaryFromReader, "", new proto.google.protobuf.Value());
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nocloud.instance.driver.vanilla.DeployResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.nocloud.instance.driver.vanilla.DeployResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nocloud.instance.driver.vanilla.DeployResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nocloud.instance.driver.vanilla.DeployResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getGroup();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      pkg_instances_proto_instances_pb.InstancesGroup.serializeBinaryToWriter
    );
  }
  f = message.getGroupDataMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(2, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.google.protobuf.Value.serializeBinaryToWriter);
  }
};


/**
 * optional nocloud.instances.InstancesGroup group = 1;
 * @return {?proto.nocloud.instances.InstancesGroup}
 */
proto.nocloud.instance.driver.vanilla.DeployResponse.prototype.getGroup = function() {
  return /** @type{?proto.nocloud.instances.InstancesGroup} */ (
    jspb.Message.getWrapperField(this, pkg_instances_proto_instances_pb.InstancesGroup, 1));
};


/**
 * @param {?proto.nocloud.instances.InstancesGroup|undefined} value
 * @return {!proto.nocloud.instance.driver.vanilla.DeployResponse} returns this
*/
proto.nocloud.instance.driver.vanilla.DeployResponse.prototype.setGroup = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.nocloud.instance.driver.vanilla.DeployResponse} returns this
 */
proto.nocloud.instance.driver.vanilla.DeployResponse.prototype.clearGroup = function() {
  return this.setGroup(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.nocloud.instance.driver.vanilla.DeployResponse.prototype.hasGroup = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * map<string, google.protobuf.Value> group_data = 2;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.google.protobuf.Value>}
 */
proto.nocloud.instance.driver.vanilla.DeployResponse.prototype.getGroupDataMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.google.protobuf.Value>} */ (
      jspb.Message.getMapField(this, 2, opt_noLazyCreate,
      proto.google.protobuf.Value));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.nocloud.instance.driver.vanilla.DeployResponse} returns this
 */
proto.nocloud.instance.driver.vanilla.DeployResponse.prototype.clearGroupDataMap = function() {
  this.getGroupDataMap().clear();
  return this;};


goog.object.extend(exports, proto.nocloud.instance.driver.vanilla);
